repos:
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
    - id: docformatter
      args: ["--in-place", "-r", "--force-wrap"]
